ALTER TABLE PUBLIC.SUPERHEROES ADD STATUS VARCHAR(8) NOT NULL;
ALTER TABLE PUBLIC.SUPERHEROES ADD CREATED_AT TIMESTAMP DEFAULT NOW();
ALTER TABLE PUBLIC.SUPERHEROES ADD UPDATED_AT TIMESTAMP DEFAULT NOW();

insert into PUBLIC.SUPERHEROES (NAME, POWER, STATUS) VALUES
('SUPERMAN', 'SPIDER', 'ACTIVE'),
('AQUAMAN', 'WATER', 'ACTIVE'),
('SUPERMAN', 'STRENGTH', 'ACTIVE'),
('MANOLITO EL FUERTE', 'VELOCITY', 'ACTIVE'),
('MANCO', 'VELOCITY', 'INACTIVE'),
('BATMAN', 'RICH', 'ACTIVE');