insert into PUBLIC.SUPERHEROES (NAME, POWER, STATUS) VALUES
('SUPERMAN', 'SPIDER', 'ACTIVE'),
('AQUAMAN', 'WATER', 'ACTIVE'),
('SUPERMAN', 'STRENGTH', 'ACTIVE'),
('MANOLITO EL FUERTE', 'VELOCITY', 'ACTIVE'),
('MANCO', 'VELOCITY', 'INACTIVE'),
('BATMAN', 'RICH', 'ACTIVE');